name: 'Tag PRs with merge conflicts'
on:
    push:
    pull_request_target:
        types: [synchronize]

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: Check if PRs are dirty
              uses: eps1lon/actions-label-merge-conflict@releases/2.x
              with:
                  dirtyLabel: 'conflictos'
                  removeOnDirtyLabel: 'conflictos'
                  repoToken: '${{ secrets.GITHUB_TOKEN }}'
                  commentOnDirty: '⚠️ Esta Pull Request tiene conflictos. Por favor, resuelvelos antes de que podamos evaluar los cambios.'
                  commentOnClean: '✅ ¡Los conflictos han sido resuletos! Un colaborador revisará pronto la Pull Request.'
